### ISSUE TITLE
mapmap version not working with mingW64

### ISSUE THREAD

**Issue by neoaurion** [nmoehrle/mvs-texturing#101]
Hi,
since the integration of mapmap, I'm not able to build mvs with mingW64 on windows (mvs-texturing/elibs/mapmap/mapmap/source/vector_math.impl.h:3588:26: error: cast from 'mapmap::_s_t<double, 4>* {aka double*}' to 'long unsigned int' loses precision [-fpermissive]
     if(!((unsigned long) ptr & v_get_mask<double, 4>()))). 
I reverted back to last commit without mapmap and everything works fine. Does anyone building with Visual studio has experienced the same thing ?
Thank you for your help.

**Comment by toke500** [comment]
Hi,

I know this issue is rather old, but if you replace "long unsigned int" with "long long usigned int", it should compile.

**Comment by neoaurion** [comment]
Yep it's working thanks
