### ISSUE TITLE
Texture boundaries from view_selection_model

### ISSUE THREAD

**Issue by smathermather** [nmoehrle/mvs-texturing#102]
Is it possible to output the texture boundaries without the text being written to those boundaries, i.e. solid colors?:

https://github.com/nmoehrle/mvs-texturing/blob/master/apps/texrecon/texrecon.cpp#L206

**Comment by nmoehrle** [comment]
There is no command line option to do it, but you could simply comment out the ["rendering" of numbers](https://github.com/nmoehrle/mvs-texturing/blob/3840a53de3a21c955571b6214f5b4721e11d4a97/libs/tex/generate_debug_embeddings.cpp#L93).

**Comment by smathermather** [comment]
Got it. Thanks!
