### ISSUE TITLE
[Question] Reducing memory usage

### ISSUE THREAD

**Issue by pierotofy** [nmoehrle/mvs-texturing#103]
This is not a really an issue, I just had a question: if I was interested in possibly reducing the memory usage of the program (perhaps in exchange for a speed tradeoff), what parts of the code should I focus my attention to? I thought I'd ask before starting a profiler tool.

Thank you for any help :smile:

**Comment by nmoehrle** [comment]
The last time I checked the two memory usages have been the [data cost table](https://github.com/nmoehrle/mvs-texturing/blob/master/apps/texrecon/texrecon.cpp#L88) and the matrices that are constructed during [poisson blending](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/poisson_blending.cpp#L122) within the local seam leveling.

You might be able to reduce the memory footprint of the local seam leveling by switching to a different solver or reducing the adjustment strip size, however, the second option will degrade the result.

Regarding the data costs at the time of writing I needed fast row and column wise access which meant that I am still storing every cost twice. I am not sure if this is still required, after moving to mapmap as graph solver, and could reduce the memory footprint of the view selection significantly.

While I can't currently look into memory optimizations myself, I would be happy to assist you as good as I can and would love to merge patches upstream.

Best wishes,
Nils

**Comment by pierotofy** [comment]
Thanks @nmoehrle, I'll start from your suggestions.

**Comment by dongshengLiu** [comment]
I have tested that the most memory-consuming step is to solve the MRF. The variable “mrfs” occupies a lot of memory. Just rewriting the data cost table does not seem to greatly reduce the memory consumption. Is there a more memory-saving way to solve the MRF?

**Comment by dongshengLiu** [comment]
> Thanks @nmoehrle, I'll start from your suggestions.

Excuse me, have you tested the maximum memory consumption after rewriting the data cost table?
