### ISSUE TITLE
Does anybody know how to build MVS-TEXTURING on the windows and vs2015

### ISSUE THREAD

**Issue by zhuixunforever** [nmoehrle/mvs-texturing#106]
Does anybody know how to build MVS-TEXTURING on the windows and vs2015

**Comment by nmoehrle** [comment]
Please have a loot at Andre's work: https://github.com/andre-schulz/mvs-texturing/tree/win32

**Comment by zhuixunforever** [comment]
I have seen this carefully, but it said that it has not tried to compile under windows. I try to compile it under windows, but I have encountered some weird problems.

**Comment by zxxsam** [comment]
have you finished this work？ @zhuixunforever
