### ISSUE TITLE
Compile error in VS2017 on win10

### ISSUE THREAD

**Issue by hastaluegoph** [nmoehrle/mvs-texturing#109]
Hello！I'm trying to compile the mvs-texturing on win 10  with VS2017,but it go wrong with the following:

Creating directories for 'ext_eigen'
2>Building Custom Rule D:/Projects/Texture/mvs-texturing/elibs/CMakeLists.txt
3>Creating directories for 'ext_mapmap'
2>CMake does not need to re-run because D:/Projects/Texture/mvs-texturing/build/elibs/CMakeFiles/generate.stamp is up-to-date.
2>Performing download step (download, verify and extract) for 'ext_eigen'
2>-- Downloading...
2>   dst='D:/Projects/Texture/mvs-texturing/build/elibs/ext_eigen/src/3.3.2.tar.gz'
2>   timeout='none'
2>-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
4>Creating directories for 'ext_mve'
5>Creating directories for 'ext_rayint'
3>Building Custom Rule D:/Projects/Texture/mvs-texturing/elibs/CMakeLists.txt
3>CMake does not need to re-run because D:/Projects/Texture/mvs-texturing/build/elibs/CMakeFiles/generate.stamp is up-to-date.
3>Performing download step (git clone) for 'ext_mapmap'
4>Building Custom Rule D:/Projects/Texture/mvs-texturing/elibs/CMakeLists.txt
3>Cloning into 'mapmap'...
4>CMake does not need to re-run because D:/Projects/Texture/mvs-texturing/build/elibs/CMakeFiles/generate.stamp is up-to-date.
4>Performing download step (git clone) for 'ext_mve'
5>Building Custom Rule D:/Projects/Texture/mvs-texturing/elibs/CMakeLists.txt
5>CMake does not need to re-run because D:/Projects/Texture/mvs-texturing/build/elibs/CMakeFiles/generate.stamp is up-to-date.
5>Performing download step (git clone) for 'ext_rayint'
4>Cloning into 'mve'...
5>Cloning into 'rayint'...
5>Branch 'cuda' set up to track remote branch 'cuda' from 'origin'.
5>Switched to a new branch 'cuda'
5>No update step for 'ext_rayint'
5>No patch step for 'ext_rayint'
5>No configure step for 'ext_rayint'
5>No build step for 'ext_rayint'
5>No install step for 'ext_rayint'
5>Completed 'ext_rayint'
3>Your branch is up to date with 'origin/master'.
3>Already on 'master'
3>No update step for 'ext_mapmap'
3>No patch step for 'ext_mapmap'
3>No configure step for 'ext_mapmap'
3>No build step for 'ext_mapmap'
3>No install step for 'ext_mapmap'
3>Completed 'ext_mapmap'
4>Your branch is up to date with 'origin/master'.
4>Already on 'master'
4>No update step for 'ext_mve'
4>No patch step for 'ext_mve'
4>No configure step for 'ext_mve'

-- Retrying...
2>-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
2>-- Retry after 5 seconds (attempt #2) ...
2>-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
2>-- Retry after 5 seconds (attempt #3) ...
2>-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
2>-- Retry after 15 seconds (attempt #4) ...
2>-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
2>-- Retry after 60 seconds (attempt #5) ...
2>-- Using src='https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz'
2>CMake Error at D:/Projects/Texture/mvs-texturing/build/elibs/ext_eigen/src/ext_eigen-stamp/download-ext_eigen.cmake:159 (message):
2>  Each download failed!
2>
2>CUSTOMBUILD : error : downloading 'https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz' failed
2>         status_code: 7
2>         status_string: "Couldn't connect to server"
2>         log:
2>         --- LOG BEGIN ---
2>         timeout on name lookup is not supported
2>    Trying 18.205.93.1...
2>
2>  TCP_NODELAY set
2>
2>  connect to 18.205.93.1 port 443 failed: Timed out
2>
2>    Trying 18.205.93.2...
2>
2>  TCP_NODELAY set
2>
2>  connect to 18.205.93.2 port 443 failed: Timed out
2>
2>    Trying 18.205.93.0...
2>
2>  TCP_NODELAY set
2>
2>  connect to 18.205.93.0 port 443 failed: Timed out
2>
2>  Failed to connect to bitbucket.org port 443: Timed out
2>
2>  Closing connection 0

so ,what should i do?

**Comment by nmoehrle** [comment]
Since it is a timeout and the link is up, as far as I can tell, please just try to rerun.
