### ISSUE TITLE
The inspect results was failed

### ISSUE THREAD

**Issue by LamboAventador** [nmoehrle/mvs-texturing#110]
when I run the last command, it shows it's a dictionary, and I can't find textured.obj in this folder.
Did anyone else met the same problem? I'm  new in Linux, thanks for helping!

bo@bo-K45VD:~$ $codedir/mve/apps/umve textured.obj
bash: /home/bo/download/3d/compile/mve/apps/umve: it is a dictionary.

**Comment by nmoehrle** [comment]
The executable is called umve and is within that directory (_/home/bo/download/3d/compile/mve/apps/umve*/umve*_). I have no access to the website anymore so I cannot fix the documentation there...

**Comment by LamboAventador** [comment]
@nmoehrle Thanks for your reply, and I found the textured.obj in imdir.
