### ISSUE TITLE
Inconsistent view selection

### ISSUE THREAD

**Issue by lufi0401** [nmoehrle/mvs-texturing#113]
Hi,
I am using mvs-texturing and notice that the result differs between runs with same parameters (`--keep_unseen_faces -v`), i.e. different views maybe selected for the same face. Is there any parameters we may utilize to control for a more consistent result?
Thanks.

**Comment by lufi0401** [comment]
Thanks! Will explore that

**Comment by nmoehrle** [comment]
Closing this, please reopen if your issue is not resolved.
