### ISSUE TITLE
mapmap compile

### ISSUE THREAD

**Issue by kuangqi93** [nmoehrle/mvs-texturing#121]
Excuse me, when I execute make, it shows the error
"mvs-texturing/libs/tex/view_selection.cpp:62:67: error: invalid conversion from ‘mapmap::Graph<float>*’ to ‘mapmap::luint_t {aka long unsigned int}’ [-fpermissive]
     mapmap::UnaryTable<cost_t, simd_w> unaries(&mgraph, &label_set)"

I think it might be that the mapmap version is not correct. Is that right?

**Comment by nh2** [comment]
This combo of versions worked for me: https://github.com/nmoehrle/mvs-texturing/issues/120#issuecomment-541404178
