### ISSUE TITLE
texrecon duplicates / creates additional vertices

### ISSUE THREAD

**Issue by nh2** [nmoehrle/mvs-texturing#135]
There seem to be many cases where `texrecon`, when writing out a `.ply` file, makes up additional vertices, destroying connectivity information.

For example, for a mesh with

```
Vertices: 15001
Faces: 30000
```

after `texrecon` it has:

```
Vertices: 22922
Faces: 29985
```

This happens even when the input mesh is a nice 2-manifold.

### Visual example

![image](https://user-images.githubusercontent.com/399535/76256362-1b1ccf00-6250-11ea-8653-3970d4ded00b.png)

In the previous image, Blender shows how the selected edge is properly connected (its end vertices' edges are all half-yellow).

But after `texrecon` on that mesh, that edge is disconnected (in the `.ply` texrecon writes):

![image](https://user-images.githubusercontent.com/399535/76256391-27a12780-6250-11ea-9da0-73678c7d24cc.png)

---

Are you aware of this issue?

Any idea what might cause it, before we dive into debugging it?

**Comment by nmoehrle** [comment]
I am confused texrecon writes a .obj as output and that has exactly the vertices of the input mesh, it will even keep unreferenced vertices such that the index is the same. Can it be that your conversion into a ply file creates duplicate vertices? Obj allows you to write one texture coordinate per face and vertex so a duplication of vertices is not necessary, for your ply flavor that might be different. How do you convert into a ply file?

**Comment by nh2** [comment]
You are right. I have confirmed that the written obj does not have this problem. It was some post-processing on my side. Sorry for the confusion.

**Comment by nmoehrle** [comment]
No worries, glad I could help :-)
