### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by lz199144** [nmoehrle/mvs-texturing#15]
Core dumped occurred, and the message is that: 
Load and prepare mesh: 
PLY Loader: comment Export generated by libmve
Reading PLY: 136733 verts... 270136 faces... done.
	Removed 5 redundant faces.
Generating texture views: 
Initializing scene with 79 views...
Initialized 79 views (max ID is 78), took 58ms.
        Loading 100%... done. (Took 10.119s)                                    
Building adjacency graph: 
        Adding edges 94%...texrecon: /home/lz/Documents/texture/texrecon/libs/tex/UniGraph.h:107: bool UniGraph::has_edge(std::size_t, std::size_t) const: Assertion `n1 < num_nodes() && n2 < num_nodes()' failed.
Aborted (core dumped)
What's wrong?

**Comment by SatishRajagopal** [comment]
I'm having the same issue. In fact I tried running on data which gave me results with an earlier version.

**Comment by dritsher** [comment]
I having the same issues as well.

**Comment by nmoehrle** [comment]
Sorry guys, the bug was introduced a week ago with commit 81a00549f7 and occurs only if redundant faces are removed. I am currently traveling and but I will fix it as soon as I can get a hold of a laptop, potentially tomorrow. 

apps/texrecon/texrecon.cpp:48 vertex_infos is not updated after faces have been removed

**Comment by SatishRajagopal** [comment]
Thanks Nils Moehrle. I will test it out as soon as I get some time.

**Comment by dritsher** [comment]
It work better, but I still aborted with this code:

Calculating face qualities 100%... done. (Took 95.346s)                 
	Maximum quality of a face within an image: 1242.11
	Clamping qualities to 106.928 within normalization.
	Writing data cost file... done.
	3324 faces have not been seen by a view.
	Iteration	Energy		Runtime
	0		4.70783e+12	0.119
	1		1.53574e+12	1.17
	2		1.53274e+12	1.889
	3		1.53245e+12	2.566
	4		1.53241e+12	3.239
	5		1.53241e+12
	Converged
	Took: 127.957s
Generating texture patches:
	Running... Assertion failed: (min_x >= 0 && min_y >= 0), function generate_candidate, file /Users/davidritsher/mvs-texturing/mvs-texturing/libs/tex/generate_texture_patches.cpp, line 74.
Abort trap: 6
davids-mbp:lionHanau davidritsher$

**Comment by nmoehrle** [comment]
I revised the assertions with ba44473, hopefully this resolves the issue.

**Comment by SatishRajagopal** [comment]
The update fixed the issue. Sorry for the late reply. I just finished testing today.
