### ISSUE TITLE
https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz link broken

### ISSUE THREAD

**Issue by mattbrown11** [nmoehrle/mvs-texturing#158]
Looks like the link to https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz is broken.

**Comment by mattbrown11** [comment]
URL             https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.tar.gz
    URL_MD5         02edfeec591ae09848223d622700a10b

seems to work

**Comment by BlGene** [comment]
see https://github.com/nmoehrle/mvs-texturing/pull/153

**Comment by nmoehrle** [comment]
Thank you :-) Should be fixed with #164 now.
