### ISSUE TITLE
NVMCameraInfo

### ISSUE THREAD

**Issue by wyxiaoyeliming** [nmoehrle/mvs-texturing#159]
libs/tex/generate_texture_views.cpp:182:11:
error:'NVMCameraInfo' is not a member of mve

**Comment by IndoorVision** [comment]
Hello, I encountered the same problem, how did you solve it?

**Comment by IndoorVision** [comment]
I have solved it.
from andre-schulz : there were some changes in the MVE repo recently. Try renaming NVMCameraInfo to AdditionalCameraInfo.
