### ISSUE TITLE
eigen-lib download broken

### ISSUE THREAD

**Issue by PriNova** [nmoehrle/mvs-texturing#162]
Hi Mr. Moehrle.

The downloaf-link of eigen has changed. The eigen-libs are now hosted at gitlab.

In the texrecon/elibs/CMakeLists.txt @ L:25 the URL and MD5 need to be changed.

Solution:

URL: https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.tar.gz
MD5: 02edfeec591ae09848223d622700a10b

Thank you for your great lib.

**Comment by nmoehrle** [comment]
Thank you :-) Should be fixed with #164
