### ISSUE TITLE
Support new MVE file format

### ISSUE THREAD

**Issue by nmoehrle** [nmoehrle/mvs-texturing#17]
The underlying MVE library will change its file format in version 2.0, as the transition is made it should be supported in a branch.

**Comment by nmoehrle** [comment]
Commit 9fb46f4562 introduces the mve2 branch which is compatible with the mve2 branch of simonfuhrmann/mve, however, this branch is currently untested.

**Comment by KevinCain** [comment]
Thanks @nmoehrle for addressing the new MVE file format.  I see you have a new branch for mve2; is that ready or awaiting more work?

**Comment by nmoehrle** [comment]
I have used it on top of the current master branch for a while now and everything works smoothly. However, I want to keep it separate for the moment because there might be some more changes in the next weeks.

**Comment by KevinCain** [comment]
Part way through compiling the MVE2 branch of `texrecon`, `make` passes an error at the following line:
https://github.com/nmoehrle/mvs-texturing/blob/master/libs/mrf/Graph.h/#L30

From the error 'invalid pure specifier' error it seems that the compiler wants a `0` value or perhaps `nullptr`?

I'm compiling with 'cmake' 2.8 and 'gcc' 4.9.0 under SuSE Linux.  Error context below:

```
[ 44%] Building CXX object libs/mrf/CMakeFiles/mrf.dir/Graph.cpp.o
In file included from /home/cain/texrecon/libs/mrf/Graph.cpp:1:
/home/cain/texrecon/libs/mrf/Graph.h:30: error: invalid pure specifier (only `= 0' is allowed) before ‘;’ token
In file included from /home/cain/texrecon/libs/mrf/GCOGraph.h:7,
                 from /home/cain/texrecon/libs/mrf/Graph.cpp:4:
```

**Comment by KevinCain** [comment]
I was able to direct `cmake` to the correct version of `gcc` by explicitly setting the following variables in .bashrc:

```
export CC=/opt/dev/gcc/gcc-4.9.0/bin/gcc
export CXX=/opt/dev/gcc/gcc-4.9.0/bin/g++
```

**Comment by nmoehrle** [comment]
It appears that cmake is always using the first compiler it finds. It searches several paths but beforehand it looks into the environment variables. There is currently no way to tell cmake to search for a compiler above some "compiler independent" version. I can check the gcc version used manually and print out an error (within cmake) or mention this thread in the readme. What would you have preferred?

**Comment by KevinCain** [comment]
Why not both?  That should make it trivial for others to catch and fix similar cases.

Thanks again for your fast, helpful posts and for quickly updating to the new MVE file format.
