### ISSUE TITLE
how can i fix this optimization error in global_seam_leveling function

### ISSUE THREAD

**Issue by kumo-park** [nmoehrle/mvs-texturing#170]
hello. nmoehrle
i am using your great code for texturing.
but i got stuck in some problem.

the thing i am trying to do is to make unseen faces textured with vertex color.

for example
<img width="856" alt="Screen Shot 2021-05-28 at 8 53 52 AM" src="https://user-images.githubusercontent.com/84943662/119910762-d08d8c80-bf92-11eb-89d3-41935b35df58.png">
picture 1. this is unseen faces

i try to give a patch to unseen faces in picture 1. so i did with below steps in generate_texture_patches function
a. create blank image for an unseen face (mve::FloatImage::Ptr image = mve::FloatImage::create(imgW,imgH,imgC))
b. fill the image with vertex color with interpolation algorithm
c. extract patch from that image
d. register that patch into a patch list
(
TexturePatch::Ptr texture_patch= TexturePatch::create(texture_views->size()+1+i, faces, texcoords, image)
texture_patches->push_back(texture_patch)
)
e. make a VertexProjectionInfo and then push the info into a list
(
VertexProjectionInfo info = {texture_patch_id, projection, {face_id}}
vertex_projection_infos->at(vertex_id).push_back(info)
)
f. iterate steps from a~e for each unseen face

after these step i got a result like below picture
<img width="785" alt="Screen Shot 2021-05-28 at 8 54 24 AM" src="https://user-images.githubusercontent.com/84943662/119911290-03845000-bf94-11eb-990f-3ab3b7ceff4d.png">
picture2. this looks what i expected

but sometime the result is changed in global_seam_leveling function like this
<img width="800" alt="Screen Shot 2021-05-28 at 8 53 00 AM" src="https://user-images.githubusercontent.com/84943662/119911436-480feb80-bf94-11eb-96cc-26d048558a8e.png">
picture 3. wrong result from global_seam_leveling function

it's like an alien movie.
so i want you to give me a good intuition to fix this problem.
thank you~

**Comment by nmoehrle** [comment]
How much padding do your artificial patches have? I could imagine that this is an out of bounds access when sampling the edges because the texture coordinates are too close to the border of the artificial atlas patches for interpolation.

**Comment by kumo-park** [comment]
> How much padding do your artificial patches have? I could imagine that this is an out of bounds access when sampling the edges because the texture coordinates are too close to the border of the artificial atlas patches for interpolation.
