### ISSUE TITLE
Texture broken down into Weird, small texture patches

### ISSUE THREAD

**Issue by mali-tintash** [nmoehrle/mvs-texturing#173]
I am not too sure what is causing these small pieces of texture, and What is causing them not to be a part of the bigger texture island? The door is fairly flat and it can be seen in the untextured mesh (ply at the provided link).

The mesh (.ply) and the source images along with the textured obj can be found at the following link:
https://drive.google.com/drive/folders/1feALwHFn9dMEnZ9fcCPTwBaOHR7OSqZd?usp=sharing

Disclaimer:
I had to change a couple of things in the code. Specifically, 
![image](https://user-images.githubusercontent.com/53075248/121351499-473c6980-c945-11eb-926c-40df5f9a7d78.png)
does this 0.5 offset make any difference?

and my lookAt camera is pointing inwards so 
![image](https://user-images.githubusercontent.com/53075248/121351324-13f9da80-c945-11eb-819d-49ea7c3a1bec.png)

![image](https://user-images.githubusercontent.com/53075248/121349291-c5e3d780-c942-11eb-911d-272d04379379.png)

![atlas1_material0000_map_Kd](https://user-images.githubusercontent.com/53075248/121349195-a8167280-c942-11eb-87bb-5a0e52dd6be5.png)

![atlas1_material0001_map_Kd](https://user-images.githubusercontent.com/53075248/121349223-b06ead80-c942-11eb-84cc-d4260dc72811.png)

**Comment by mali-tintash** [comment]
This was textured using a single view. You can see the striped pattern (sort of)
![image](https://user-images.githubusercontent.com/53075248/121470456-b06cbd00-c9d7-11eb-8b51-398135062e15.png)

**Comment by nmoehrle** [comment]
Could it be that the mesh consists of several connected components?
