### ISSUE TITLE
Texture from RGB-D camera is not aligned to 3D mesh

### ISSUE THREAD

**Issue by wodndb** [nmoehrle/mvs-texturing#177]
I want to texturing 3D mesh using RealSense D415 camera.

RealSense D415 Camera is RGB-D camera which has two IR camera to generating stereo depth image and one color camera.

1. I captured a point cloud and color image from D415 camera.

2. I reconstructed point cloud to ply format 3D mesh.

3. I prepared cam file which include intrinsic and extrinsic parameter of D415 color camera.

4. I build https://github.com/andre-schulz/mvs-texturing to use texrecon in windows.

Extrinsic parameter of color camera is below matrix.

![image](https://user-images.githubusercontent.com/8624058/123591240-ad225f80-d826-11eb-9147-029a2285681c.png)

And result is this (below image). Texture is not aligned.

![image](https://user-images.githubusercontent.com/8624058/123591721-51a4a180-d827-11eb-8b00-a499fcb0b1c6.png)

And I translate the mesh to (-0.015, 0, 0) and change the extrinsic parameter to identity matrix.

And a result like this. (below image) Texture is aligned.

![image](https://user-images.githubusercontent.com/8624058/123592025-acd69400-d827-11eb-8d46-bbd63f229c7b.png)

Why these two things are differ?

I attach two data set what I show in upper images.
[default.zip](https://github.com/nmoehrle/mvs-texturing/files/6723996/default.zip)
[mesh_translated.zip](https://github.com/nmoehrle/mvs-texturing/files/6723997/mesh_translated.zip)

Thanks.

**Comment by wodndb** [comment]
I'm sorry. I mistake to make data set. This issue is not correct.

**Comment by lihui1998** [comment]
> I'm sorry. I mistake to make data set. This issue is not correct.

Can you tell me how to use cam file,thanks

**Comment by wodndb** [comment]
@lihui1998 I generated cam file based on this description.
https://github.com/nmoehrle/mvs-texturing/blob/master/apps/texrecon/arguments.cpp#L33
