### ISSUE TITLE
Issue for texturing 3D

### ISSUE THREAD

**Issue by danglu999** [nmoehrle/mvs-texturing#180]
Hi,
A lot of thanks for your great works!
I encountered an issue on texturing a mesh which is reconstructed by [NeuralRecon](https://github.com/zju3dv/NeuralRecon), images are extracted from a video (resolution: 640x480).

The following pictures demonstrate the issue.
**Generated mesh:**
<img width="808" alt="mesh" src="https://user-images.githubusercontent.com/69308651/132209573-95d66b1e-947a-47cc-979a-1ccced1f82a0.png">
**A corner of real situation**
<img width="1025" alt="real_world2" src="https://user-images.githubusercontent.com/69308651/132210210-4f876e82-7f3f-4ab8-a0d6-57fb74df8585.png">

**Textured mesh by applying mvs-texturing**

<img width="844" alt="Screen Shot 2021-09-07 at 11 25 33" src="https://user-images.githubusercontent.com/69308651/132279751-8bcab087-6426-423c-8b55-80fc8ee32098.png">

Would you please give me some advice and how should I improve it.
Thanks!

**Comment by cucdengjunli** [comment]
same question

**Comment by DeadlyMagikarps** [comment]
Hate to re-open a question. But what causes it to do this texture drifting? I've been experiencing similar results... Seems like frame mismatch.
