### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by andapka** [nmoehrle/mvs-texturing#186]
I compiled the project and recieved the following error:
`
Your branch is up to date with 'origin/master'.
[ 42%] No update step for 'ext_mapmap'
[ 44%] No patch step for 'ext_mapmap'
[ 45%] No configure step for 'ext_mapmap'
[ 47%] No build step for 'ext_mapmap'
[ 49%] No install step for 'ext_mapmap'
[ 50%] Completed 'ext_mapmap'
[ 50%] Built target ext_mapmap
In file included from arguments.cc:18:
../../libs/util/arguments.h:126:9: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  126 |         throw(util::Exception);
      |         ^~~~~
../../libs/util/arguments.h:129:9: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  129 |         throw(util::Exception);
      |         ^~~~~
arguments.cc:69:5: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   69 |     throw(util::Exception)
      |     ^~~~~
arguments.cc:81:5: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   81 |     throw(util::Exception)
      |     ^~~~~
In file included from /usr/include/string.h:495,
                 from /usr/include/c++/9/cstring:42,
                 from file_system.cc:15:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘const char* util::fs::get_home_dir()’ at file_system.cc:226:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 4096 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘const char* util::fs::get_app_data_dir()’ at file_system.cc:199:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 4096 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 52%] No install step for 'ext_mve'
[ 54%] Completed 'ext_mve'
[ 54%] Built target ext_mve
[ 59%] Building CXX object libs/tex/CMakeFiles/tex.dir/build_adjacency_graph.cpp.o
[ 59%] Building CXX object libs/tex/CMakeFiles/tex.dir/calculate_data_costs.cpp.o
[ 59%] Building CXX object libs/tex/CMakeFiles/tex.dir/build_obj_model.cpp.o
[ 61%] Building CXX object libs/tex/CMakeFiles/tex.dir/generate_texture_atlases.cpp.o
[ 66%] Building CXX object libs/tex/CMakeFiles/tex.dir/global_seam_leveling.cpp.o
[ 66%] Building CXX object libs/tex/CMakeFiles/tex.dir/generate_texture_views.cpp.o
[ 66%] Building CXX object libs/tex/CMakeFiles/tex.dir/generate_texture_patches.cpp.o
[ 67%] Building CXX object libs/tex/CMakeFiles/tex.dir/histogram.cpp.o
[ 69%] Building CXX object libs/tex/CMakeFiles/tex.dir/generate_debug_embeddings.cpp.o
[ 71%] Building CXX object libs/tex/CMakeFiles/tex.dir/material_lib.cpp.o
[ 72%] Building CXX object libs/tex/CMakeFiles/tex.dir/local_seam_leveling.cpp.o
[ 74%] Building CXX object libs/tex/CMakeFiles/tex.dir/obj_model.cpp.o
[ 76%] Building CXX object libs/tex/CMakeFiles/tex.dir/poisson_blending.cpp.o
[ 77%] Building CXX object libs/tex/CMakeFiles/tex.dir/prepare_mesh.cpp.o
[ 79%] Building CXX object libs/tex/CMakeFiles/tex.dir/texture_atlas.cpp.o
[ 83%] Building CXX object libs/tex/CMakeFiles/tex.dir/seam_leveling.cpp.o
[ 83%] Building CXX object libs/tex/CMakeFiles/tex.dir/rectangular_bin.cpp.o
[ 84%] Building CXX object libs/tex/CMakeFiles/tex.dir/texture_patch.cpp.o
[ 86%] Building CXX object libs/tex/CMakeFiles/tex.dir/texture_view.cpp.o
[ 88%] Building CXX object libs/tex/CMakeFiles/tex.dir/timer.cpp.o
[ 89%] Building CXX object libs/tex/CMakeFiles/tex.dir/tri.cpp.o
[ 91%] Building CXX object libs/tex/CMakeFiles/tex.dir/uni_graph.cpp.o
[ 93%] Building CXX object libs/tex/CMakeFiles/tex.dir/view_selection.cpp.o
In file included from /home/andapka/Projects/mvs-texturing/elibs/mapmap/mapmap/header/graph.h:81,
                 from /home/andapka/Projects/mvs-texturing/elibs/mapmap/mapmap/header/color.h:16,
                 from /home/andapka/Projects/mvs-texturing/elibs/mapmap/mapmap/full.h:18,
                 from /home/andapka/Projects/mvs-texturing/libs/tex/view_selection.cpp:14:
/home/andapka/Projects/mvs-texturing/elibs/mapmap/mapmap/source/graph.impl.h:30:10: fatal error: mapmap/dset.h: No such file or directory
   30 | #include <mapmap/dset.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libs/tex/CMakeFiles/tex.dir/build.make:384: libs/tex/CMakeFiles/tex.dir/view_selection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/andapka/Projects/mvs-texturing/libs/tex/texture_view.cpp: In constructor ‘tex::TextureView::TextureView(std::size_t, const mve::CameraInfo&, const string&)’:
/home/andapka/Projects/mvs-texturing/libs/tex/texture_view.cpp:27:30: warning: catching polymorphic type ‘class util::Exception’ by value [-Wcatch-value=]
   27 |     } catch (util::Exception e) {
      |                              ^
make[1]: *** [CMakeFiles/Makefile2:277: libs/tex/CMakeFiles/tex.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

What is the reason?
OS: Ubuntu 20.04
cmake = 3.21
gcc = 9.3

Appreciate for your help

**Comment by oleg-alexandrov** [comment]
This will help: https://github.com/oleg-alexandrov/mvs-texturing/commit/b6bac864fc231ebe4c74033311c9c17bf1ed3758

**Comment by dthuerck** [comment]
The issues with `mapmap` should be resolved by now, please see if the newest version works. Thank you!
