### ISSUE TITLE
Unknown white and black texture blocks

### ISSUE THREAD

**Issue by Habsburgg** [nmoehrle/mvs-texturing#209]
![1111](https://github.com/nmoehrle/mvs-texturing/assets/56535633/23f76ba8-32e5-4796-b185-18fbc88626fc)

**Comment by Habsburgg** [comment]
Lots of black and white textures after texture mapping.

**Comment by Habsburgg** [comment]
After updating the code, it works fine

**Comment by omah03** [comment]
Hey, can I ask how did you update the code?
