### ISSUE TITLE
cmake 3.1.3 fails to build mvs-texturing

### ISSUE THREAD

**Issue by KevinCain** [nmoehrle/mvs-texturing#21]
While `cmake` 2.8 and `gcc` 4.9.0 builds `mvs-texturing` fine for me, I'm encountering downloading errors (see below) when compiling with `cmake` 3.1.3.  To duplicate, use the following steps with `cmake` 3.1.3 and `gcc` 4.9.0:

```
git clone https://github.com/nmoehrle/mvs-texturing.git texrecon
cd texrecon
mkdir build
cd build
cmake -DRESEARCH=ON . ../
make
```
Here is the error in context:
```
[ 13%] Built target ext_coldet
[ 14%] Performing download step (download, verify and extract) for 'ext_eigen'
-- downloading...
     src='http://bitbucket.org/eigen/eigen/get/3.2.1.tar.bz2'
     dst='/home/cain/texrecon/build/elibs/eigen/src/3.2.1.tar.bz2'
     timeout='none'
-- [download 100% complete]
CMake Error at /home/cain/texrecon/build/elibs/eigen/src/ext_eigen-stamp/download-ext_eigen.cmake:27 (message):
  error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.1.tar.bz2'
  failed

    status_code: 1
    status_string: "unsupported protocol"
...
  libcurl was built with SSL disabled, https: not supported!
  unsupported protocol
...
```
[A similar thread] (https://github.com/neovim/neovim/issues/1469) suggests that the problem is SSL, as suggested by the 'libcurl was built with SSL disabled' error line above.  However -- the HTTPS download attempt giving this error is just a restatement of the previous HTTP.

**Comment by nmoehrle** [comment]
I could not reproduce the error on my system so I checked which features are enabled in libcurl on my system:
```
curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```
The feature SSL is enabled and the http protocol available which is the reason why it works on my system. The question is now why a https request is attempted in the first place by cmake (and why I did not specify and https url, but that is a different matter). I could not find a change in cmake forcing https requests, but since it is preferably anyway, I think the way to go is installing libcurl with SSL enabled.

**Comment by KevinCain** [comment]
That makes sense.  I'm surprised that SSL is not enabled by default `libcurl` on my system in question, but it is a shared use system and therefore may have been disabled for security reasons.

As above, `cmake` tries your original HTTP request first, and then retries at HTTPS, so that is less of a mystery.

Thanks for testing!
