### ISSUE TITLE
project webpage is inacessiable

### ISSUE THREAD

**Issue by thomas-19** [nmoehrle/mvs-texturing#212]
Hello, 
As per your mention in the Readme file, there is a project webpage that serves as a quick guide. However, currently, the webpage http://www.gcc.tu-darmstadt.de/home/proj/texrecon/ is inaccessible. Without this guide, I'm finding it challenging to execute the program. Is there any other source of guidance that I can refer to?

**Comment by andre-schulz** [comment]
Hi @thomas-19,
you can view the old website via the Internet Archive's Wayback Machine:
https://web.archive.org/web/20211021152444/http://www.gcc.tu-darmstadt.de/home/proj/texrecon/

**Comment by thomas-19** [comment]
@andre-schulz , thank you. By the way, would it be a good idea to migrate the webpage to GitHub's Wiki?

**Comment by andre-schulz** [comment]
Sorry for the late reply, yes this sounds like a good idea!
