### ISSUE TITLE
elseif(MSVC AND MSVC_VERSION GEQUAL 1800)

### ISSUE THREAD

**Issue by Smozeley** [nmoehrle/mvs-texturing#25]
Should GEQUAL be EQUAL on line 24? I get a cmake error.

**Comment by nmoehrle** [comment]
Visual Studio versions before version [12.0](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History) (which is 1800 according to [MSVC_VERSION](https://cmake.org/cmake/help/v3.0/variable/MSVC_VERSION.html)) have no proper c++11 support, therefore the GEQUAL (greater equal) in line [22](https://github.com/nmoehrle/mvs-texturing/blob/master/CMakeLists.txt#L22) is correct.

**Comment by Smozeley** [comment]
ok that makes sense but I am referring to the syntax for "greater equal - GEQUAL". When I run cmake for vs2012 or 2013 I get the error:

CMake Error at CMakeLists.txt:22 (elseif):
  given arguments:

    "MSVC" "AND" "MSVC_VERSION" "GEQUAL" "1800"

  Unknown arguments specified

If I change the conditional check "GEQUAL" to EQUAL I get past the error but maybe it should be like this:

if((MSVC AND MSVC_VERSION GREATER 1800) OR (MSVC AND MSVC_VERSION EQUAL 1800))
or

if(NOT (MSVC AND MSVC_VERSION LESS 1800))

I don't see support for GEQUAL in CMAKE.

**Comment by nmoehrle** [comment]
I could not really figure out why I wrote GEQUAL and there is in fact no documentation for its support. Thank you for the feedback :-)
