### ISSUE TITLE
Issue Compiling Code with MSVC 2013

### ISSUE THREAD

**Issue by ssundar6087** [nmoehrle/mvs-texturing#28]
Hello,

I followed the steps mentioned in the readme and was able to compile the code using MSVC 2013 upto a certain stage. 

The project "tex" seems to have an issue wherein the following error appears during compilation : Error	

error C1001: An internal error has occurred in the compiler

I looked further into the issue and the following line seems to be triggering the issue : 

inliers.row(row) = mve_to_eigen(infos->at(row).mean_color).cast<double>();

This is line 61 in calculate_data_costs.cpp 

I looked at the issues posted here, and saw that another user had trouble with MSVC. I tried to rebuild and recompile using the MSVC fork which Andres is maintaining. I'm still seeing the same error. 

Could you please assist me with this issue?

Thanks
Sundar

**Comment by nmoehrle** [comment]
I will look into it with Andre, but in the meantime please check the template argument (```<double>```).
```inliers.row(row) = mve_to_eigen(infos->at(row).mean_color).cast<double>();```
Best wishes
Nils

**Comment by ssundar6087** [comment]
Thanks for the quick response! I will investigate the template argument and see if this can be resolved.

**Comment by nmoehrle** [comment]
Closed due to inactivity.

**Comment by xueao** [comment]
I have the same mistake,and inliers.row(row) = mve_to_eigen(infos->at(row).mean_color).cast<double>()  appears the same error too. Could you please assist me with this issue? Thanks

**Comment by andre-schulz** [comment]
Hi xueao,
which version of Visual Studio are you using?

**Comment by xueao** [comment]
Hi andre-schulz
I'm using Visual Studio 2013.

**Comment by andre-schulz** [comment]
Can you use Visual Studio 2015? It should work with that.
The thing is that MVE and texrecon will be using more and more C++11 features and VS2013 only implements a subset of those. Additionally, AFAIK VS2013 is no longer getting updates. So if you want to use newer versions of MVE and texrecon it would be best to use VS2015.

**Comment by xueao** [comment]
@andre-schulz 
Thanks for your response. I'll try again with VS2015.
