### ISSUE TITLE
removing faces not seen by any views

### ISSUE THREAD

**Issue by lulu1315** [nmoehrle/mvs-texturing#30]
hello
I noticed that texrecon removes faces that are not viewed by any views.
maybe you could give the option to keep them and assign a flat material for example.
luc

**Comment by mojovski** [comment]
+1

**Comment by fabiencastan** [comment]
Yes, it would be really useful!

**Comment by nmoehrle** [comment]
In 037e53b I have added the flag ```--keep_unseen_faces```. However, while all faces are being kept the color is more or less random and they are all parameterized exactly the same.
Please let me know if this is sufficient for your purposes.

Best,
Nils
