### ISSUE TITLE
local_seam_leveling

### ISSUE THREAD

**Issue by AlexeyIS** [nmoehrle/mvs-texturing#32]
In local_seam_leveling.cpp in local_seam_leveling function, there is a code:

        std::vector<math::Vec3f> & edge_color = edge_colors[i];
        edge_color.resize(std::ceil(max_length * 2.0f));
        for (std::size_t j = 0; j < edge_color.size(); ++j) {
                float t = static_cast<float>(j) / (edge_color.size() - 1);
                edge_color[j] = mean_color_of_edge_point(edge_projection_infos[i], *texture_patches, t); }

in case of edge_color.size() == 1, it leads to division by 0, and t = NaN 
float t = static_cast<float>(j) / (edge_color.size() - 1);
and in mean_color_of_edge_point function 
assert(0.0f <= t && t <= 1.0f);  fails

**Comment by nmoehrle** [comment]
When I wrote that code I was mainly thinking about the MVS setting where each edge should have a projection exceeding 0.5 in length. But now that I think of it, there are many applications where this may not be the case, like smaller images for texturing than reconstruction etc...

Nice catch and excellent bug report! Thank you :-)
