### ISSUE TITLE
valid_pixel(pixel)

### ISSUE THREAD

**Issue by AlexeyIS** [nmoehrle/mvs-texturing#33]
In some cases, there is an assertion fault for valid_pixel(pixel), in  texture_patch->set_pixel_value(pixel, color); inside draw_line function, which called inside local_seam_leveling function.
In this piece of code,
for (Line const & line : lines[i]) {
            draw_line(line.from, line.to, *line.color, texture_patch);}

Let me know please if you have any idea why it can happen. 
Also attached a debug log when it's not valid. 
![screen shot 2015-12-11 at 2 14 24 pm](https://cloud.githubusercontent.com/assets/1562098/11744549/8ce21f10-a011-11e5-9b7b-acf4f3b6ef9c.png)

**Comment by nmoehrle** [comment]
I am sorry but I do not know where this is coming from. To narrow the issue down could you please run the dataset again with ```--skip_hole_filling``` and without ```--keep_unseen_faces``` (if you provided the flag previously).

The strange thing is that prior to set_pixel_value there should have been a call go get_pixel_value which is also asserting valid pixels. However, in the case of holes or unseen faces no pixel values are read, therefore the check with the flags above. But nevertheless only valid pixels should be accessed...

**Comment by AlexeyIS** [comment]
I build with config you said it still the same. I think get_pixel_value validates float pixel, and it fails on int one

**Comment by nmoehrle** [comment]
Yes it does, however, if I am not mistaken the float version is also checking the same pixel (and three others) of the validity mask. According to your debug log the pixel being checked is inside the patch and thus has to be invalid in the mask. I will review my checks again.

**Comment by AlexeyIS** [comment]
Thanks! meanwhile i'll also continue to debug.

**Comment by nmoehrle** [comment]
There was an error in the conversion of the float to integer pixel coordinates.
Could you please rerun you dataset and check if this fixes the issue?

**Comment by nmoehrle** [comment]
Closed due to inactivity.

**Comment by AlexeyIS** [comment]
Funny enough, recently I got back to the code, and it fixed the problem 😂 So Thanks Nils! Better late then never😆
