### ISSUE TITLE
Build for Windows with Visual Studio 2015 fails

### ISSUE THREAD

**Issue by igorti** [nmoehrle/mvs-texturing#35]
I've been struggling to make a build for Windows and been experiencing same issues described [here](https://github.com/nmoehrle/mvs-texturing/issues/26) earlier. I did try Andres fork with no success. Here's example of few errors I'm getting:

```
'vertex_idx': index variable in OpenMP 'for' statement must have signed integral type

'edge_idx': index variable in OpenMP 'for' statement must have signed integral type	

'capture': unexpected token encountered on OpenMP 'atomic' directive

Expression following '#pragma omp atomic' has improper form

'i': index variable in OpenMP 'for' statement must have signed integral type
```
and so on...

Any ideas on what may cause these errors?

**Comment by andre-schulz** [comment]
Hi,
which branch of the fork did you use?

**Comment by igorti** [comment]
`master` branch, since it seems to contain cmake changes and is almost in sync with the original repository.

**Comment by andre-schulz** [comment]
I'm currently bringing the Windows port up to speed with Nils` latest changes. Hang on.

**Comment by andre-schulz** [comment]
Ok, I'm finally done. All modifications regarding Windows/Visual Studio are in the `cmake` branch of my fork. I've written build instructions for Windows which you can find [here](https://github.com/andre-schulz/mvs-texturing/wiki/Build-Instructions-for-Windows).
Please let me know if the issue is fixed.

**Comment by igorti** [comment]
Thanks a lot, I'll do the tests and get back with results.

**Comment by igorti** [comment]
Not so good results unfortunately as I'm getting Internal Compiler Error in `calculate_data_costs.cpp`:

`mvs-texturing\libs\tex\calculate_data_costs.cpp(283): fatal error C1001: An internal error has occurred in the compiler`

Prior to that I was having the similar error in `bundler_features.cc` when compiling MVE:

`mve\libs\sfm\bundler_features.cc(100): fatal error C1001: An internal error has occurred in the compiler`

 I got around it by excluding `mve_sfm` project since I don't need it, but then got same error in mvs-texturing.

Line numbers point at square braces, so that's weird, doesn't seem to be a code issue. I have also tried disabling Optimisation in project setting as few people recommended on StackOverflow with no luck.

I'm using Visual Studio 2015 Community Edition with C++ extensions. Any ideas on what else I can try?

**Comment by andre-schulz** [comment]
That's strange. I just compiled MVE and mvs-texturing according to the build instructions in the mvs-texturing wiki and it compiled cleanly. Which Visual Studio version are you using exactly? I've used Visual Studio 2015 Community Update 2 but it should also work with Update 1. Just to make sure I'm on the same page as you; which mvs-texturing repository/branch did you check out and compile?

**Comment by igorti** [comment]
So installing Update 2 seem to have solved the problem, it compiles without errors now. I think I didn't even have Update 1 installed before, so probably that was an issue. Thanks for helping!

**Comment by MrAirplaneLu** [comment]
@andre-schulz 
![1](https://user-images.githubusercontent.com/45754132/50572978-a5280700-0e05-11e9-88b8-e1b0774e0db5.png)
What's the problem?
