### ISSUE TITLE
Importing MVE scene on Windows fails

### ISSUE THREAD

**Issue by igorti** [nmoehrle/mvs-texturing#37]
The issue I stumbled upon on Windows when importing MVE scene is that the absolute path(which I guess one would almost always want to use) contains colon after the drive letter, like "C:\". This becomes a problem since the code splits the path by colon when trying to detect provided type of input. 

Splitting on some character is probably not a good idea, since there's always a chance that a character will occur somewhere in the path, whatever character you choose to split on. A better solution would probably be to move `EMBEDDING` part to separate parameter?

**Comment by nmoehrle** [comment]
You are right, thanks for raising the issue and thanks for the fix Andre!
I am sorry that it took so long I somehow missed the notification....

**Comment by hushanming** [comment]
Hi, I'm facing the same problem when importing bundle.nvm with the absolute path contains colon after the drive letter,like "D:\data\der_hass-20140923\bundle.nvm".The [code](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L211) does not enter the loop but exit directly when debuging here.I try it on the linux and windows but failed.So what's your view on it?Can you help me solve this problem?Thanks.
