### ISSUE TITLE
Does MVS support the multi-tiff files

### ISSUE THREAD

**Issue by xialang2012** [nmoehrle/mvs-texturing#45]
Hi, 
I used MVS to texture my mesh and it really impressed me. Now, I have some multi-tiff files (it means several bands in one tif file) which need to be textured, but I am failed to use the current version MVS to do that.
I am wonder whether there are some ways to achieve that, or is it a heavy work to revise the code?

**Comment by nmoehrle** [comment]
So as I understand you want to use multi-tiff image files to texture an object with `texrecon`.
The acronym MVS stands for Multi-View Stereo and describes a category of image-based 3D reconstruction algorithms. The main focus of our project *mvs-texturing* is the texturing of reconstructions created with those algorithms, therefore the name.

Could you give me an example of one of the multi-tiff files? Are there multiple viewpoints in one tiff file?

**Comment by xialang2012** [comment]
The multi-tiff you can download from here http://pan.baidu.com/s/1slQTyVj
The tiff file is the hyper-spectral image, that means each band in the tiff file stands for a specific band-width image for the same object.

**Comment by nmoehrle** [comment]
I'll have a look at it in the afternoon, but so far we only ever had three channel images. Theoretically our image model supports *n* channels but there is a good chance that I made assumptions in the code about the number of channels. I am going to have a look at that as well.

**Comment by nmoehrle** [comment]
After skimming the code again, there are at least some things that are not going to work with more than three channels. Outlier removal for example is assuming RGB images and changes the colorspace to YCbCr. Most of the other code could be adapted to support *n* channel images since the channels are largely processed seperately. However, we only support OBJ model with PNG textures at the moment and PNG is limited to four channels, tiff support could be added but I propably won't have time for that within the next weeks.

**Comment by xialang2012** [comment]
Thank you. I will read the code first and then try to do some revise. If I have questions I will ask you for help.

**Comment by nmoehrle** [comment]
So I had a look at the files:
```
TIFF Directory at offset 0x1091f188 (278000008)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1000 Image Length: 1000
  ...
  Extra Samples: 136<unspecified, unspecified, ...
  ...  
  Samples/Pixel: 139
  ...
```
Did I get this right, you want to texture an object with multiple 139 channel images?

As I mentioned some things (outlier removal) would have to be heavily adapted while others (seam leveling) are probably not desired.

To get the basic mapping and texture creation you should first create a scene with the images (either a mve scene or a folder with cam and image files as described in the helptext).
And then change these code segments:
- remove channel amount [check](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L54)
- rewrite the [gradient magnitude function](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/texture_view.cpp#L103)([desaturate](
https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_tools.h#L1343) allows only three and four channel images)
- create an appropriate fill color ([`math::Vec3uc(255, 0, 255)`](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_patches.cpp#L103)) although that should not have any influence...
- add a parameter for the number of channels to the [TextureAtlas constructor](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/texture_atlas.cpp#L19)
- change the limit of channels [here](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/texture_atlas.cpp#L154)
- change the file format [here](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/material_lib.cpp#L21) depending on the number of channels of the diffuse_map
- fix any arising compile issues (I will probably missed a couple of segments)

If you have questions please push your current state in a feature branch (`tiff-support`) on you fork and add locations hints like the ones in this post.

Best Nils

**Comment by xialang2012** [comment]
Thank you for your kind help. 
In fact, I am a new one about the 3D texture, and this afternoon I downloaded the paper from http://www.gcc.tu-darmstadt.de/media/gcc/papers/Waechter-2014-LTB.pdf and read it. Now, I have a basic understand about the flow path of the 3D texture. 
Next week, I will work on it. Thank you, Nils.

**Comment by xialang2012** [comment]
By the way, can we add a feature which allow us to export the textured result to the images, such as png or jpg?

**Comment by nmoehrle** [comment]
Sorry I do not understand what you mean by that.
Do you want to use the multi-tiff images just as input and still obtain a normally textured object (with texture atlases in PNG format).
Or do you want to render an object with multi-tiff textures as PNG.

All texture atlases are currently written to disk as PNG.

**Comment by xialang2012** [comment]
Sorry for that I did not make myself clear. 
I mean that can we export the image that as same as what Meshlab shows when we put the texture result into it. Or, a orthophoto image?

**Comment by xialang2012** [comment]
According to your directions, I revised the code. Besides, I also change the 
[https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L192]
to 
`mve::image::save_tiff_file(image, image_file);`
Then I used the a *.nvm file and mesh data to test the code. But it showed some errors

> terminate called after throwing an instance of 'util::FileException'
>   what():  No such file or directory

or

` what():  Cannot determine image color type`

or

`Could not load image header of`

Then I found the image_io.cc in MVE was not define how to get the header info
[https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image_io.cc#L96]

I am not exactly know how to add some codes to enhance it.

The test data I used is here:
http://pan.baidu.com/s/1cxBUyU
and command on Ubuntu 14
`./texrecon nvmCams.nvm odm_mesh.ply ./odm_textured_model -d gmi -o none `

**Comment by nmoehrle** [comment]
The last error comes from [texture_view.cpp#L26]
(https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/texture_view.cpp#L26) to avoid massive changes I would advise trying to use a mvei image instead of a tiff image at [generate_texture_views.cpp#L192](https://githuhttps://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L192). The mvei image type is designed for n channel images.

**Comment by xialang2012** [comment]
Sorry, I can not find enough information about the MVEI format except this: MVEI (arbitrary number of channels or type) from https://github.com/simonfuhrmann/mve/wiki/MVE-File-Format. Does MVEI is a binary format with a header file which just like ENVI dat format?

**Comment by nmoehrle** [comment]
I don't know the ENVI dat format, but the mvei format is just a n channel image format that MVE fully supports, so I suggested using it to temporary save the undistorted tiff image file because the `load_mvei_image_header` function is implemented and you would not have to write a `load_tiff_image_header` function.

**Comment by xialang2012** [comment]
Thank you, the mvei is the file create by makescene.
I used the makescene to import the tiff file
`makescene -i in-tif out-scene`
Then I tried sfmrecon
`sfmrecon out-scene`

> MVE SfM Reconstruction (built on Jun 18 2016, 06:07:24)
> SSE2 accelerated matching is enabled.
> SSE3 accelerated matching is enabled.
> Initializing scene with 7 views...
> Initialized 7 views (max ID is 6), took 0ms.
> Computing image features...
> Detecting features, view 7 of 7 (100%)...terminate called after throwing an instance of 'std::invalid_argument'
>   what():  Gray or color image expected
> terminate called recursively
> Aborted (core dumped)

Then I tried to revise the .nvm file to replace the image files with the mvie files which created by the makescene, but it showed

> xl@ubuntu:~/mvs/mvs-texturing/build/apps/texrecon$ ./texrecon nvmCams.nvm ./odm_mesh.ply ./odm_textured_model -d gmi -o none 
> ./texrecon (built on Jun 18 2016, 01:39:42)
> Load and prepare mesh: 
> PLY Loader: comment PCL generated
> Reading PLY: 100002 verts... 199834 faces... done.
> Warning: Zero-length normals detected: 2 face normals, 0 vertex normals
> Generating texture views: 
> NVM: Loading file...
> NVM: Number of views: 7
> NVM: Number of features: 0
>         Loading 0%...terminate called after throwing an instance of 'util::Exception'
>   what():  Cannot determine image format
> Aborted (core dumped)

~~Something wrong

**Comment by nmoehrle** [comment]
I thought about just changing the [image saving](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L192) to mvei but converting them beforehand could also work. However, you would have to change the [image loading](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L183) to `load_mvei_image` instead of `load_image`.

**Comment by nmoehrle** [comment]
Oh my bad, that doesn't work since a mvei could be a float or byte image...
I don't have time today but I will hopefully be able to look at it tomorrow.

**Comment by nmoehrle** [comment]
Working on it https://github.com/simonfuhrmann/mve/pull/240

**Comment by xialang2012** [comment]
Okay, I will try it tomorrow.

**Comment by xialang2012** [comment]
After changing  https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L183 to 
`mve::ImageBase::Ptr image = mve::image::load_mvei_file(nvm_cam.filename);`
It shows 

>  cannot convert ‘image’ (type ‘mve::ImageBase::Ptr {aka std::shared_ptr<mve::ImageBase>}’) to type ‘mve::Image<unsigned char>::ConstPtr {aka std::shared_ptr<const mve::Image<unsigned char> >}’
>              (image, mve_cam.flen, nvm_cam.radial_distortion);

It seems the ImageBase is the base class, we still need to make some change 
```
class Image : public TypedImageBase<T>
class TypedImageBase : public ImageBase
```

**Comment by nmoehrle** [comment]
This is what the pull request (https://github.com/simonfuhrmann/mve/pull/241/commits/812e5944d8bdc3f848ae83e92d60b7f121bd725d) was meant for, but you can also do this yourself by using the `std::static_pointer_cast<ByteImage>` (after checking for the correct type...).

**Comment by nmoehrle** [comment]
In retrospective a `std::dynamic_pointer_cast` might be better since it does a runtime check  for the type... Anyway, the pull request is going to be merged within the next days.

**Comment by xialang2012** [comment]
I works now, but I have to comment this line 
`mve::image::save_mvei_file(image, image_file);`
It will cause 

> *** Error in `./texrecon': double free or corruption (out): 0x00007f9830000db0 ***

Besides, the textured material file `odm_textured_model_material0000_map_Kd.tiff` seems only contain 3 bands, even if I use 5 bands mvei file as input.

**Comment by nmoehrle** [comment]
Did you change the number of channels in the Texture [TextureAtlas constructor](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/texture_atlas.cpp#L23)?

I cannot really help you if you do not push you changes...

**Comment by xialang2012** [comment]
Sorry, it's here https://github.com/xialang2012/mvs-texturing/commit/84d9a66a1562704464239e36de5f808d4edfb8eb

**Comment by nmoehrle** [comment]
It is unclear to me how you managed to load a five channel images with that state.

I am implementing support for n channel images in the [n-channel-images](https://github.com/nmoehrle/mvs-texturing/commits/n-channel-images) branch. At the moment you have to manually change the channel number [here](https://github.com/nmoehrle/mvs-texturing/blob/n-channel-images/libs/tex/generate_texture_atlases.cpp#L120).

**Comment by xialang2012** [comment]
It works now, except for some double free errors.
