### ISSUE TITLE
Build fails on MAC

### ISSUE THREAD

**Issue by lizhengning** [nmoehrle/mvs-texturing#46]
Fail with following error
`Undefined symbols for architecture x86_64:
  "acc::BVHTree<unsigned int, math::Vector<float, 3> >::NAI", referenced from:
      acc::BVHTree<unsigned int, math::Vector<float, 3> >::bsplit(unsigned int, std::__1::vector<acc::AABB<math::Vector<float, 3> >, std::__1::allocator<acc::AABB<math::Vector<float, 3> > > > const&) in libtex.a(calculate_data_costs.cpp.o)
      acc::BVHTree<unsigned int, math::Vector<float, 3> >::ssplit(unsigned int, std::__1::vector<acc::AABB<math::Vector<float, 3> >, std::__1::allocator<acc::AABB<math::Vector<float, 3> > > > const&) in libtex.a(calculate_data_costs.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [apps/texrecon/texrecon] Error 1
make[1]: *** [apps/texrecon/CMakeFiles/texrecon.dir/all] Error 2`

**Comment by nmoehrle** [comment]
This is an issue of [rayint](https://github.com/nmoehrle/rayint)/[libacc](https://github.com/nmoehrle/libacc) and occurs if compiler do not resolve `constexpr`'s at compile time. This should not happen in a release build.

I have not found a clean way to resolve this issue, I am happy for ideas.

**Comment by nmoehrle** [comment]
This [line](https://github.com/nmoehrle/rayint/blob/cuda/libs/acc/bvh_tree.h#L42) is causing the issue.

**Comment by lizhengning** [comment]
Thanks! I am trying other complier.

**Comment by nmoehrle** [comment]
Could you try changing it to a define like [this](https://github.com/nmoehrle/rayint/blob/premake/libs/acc/bvh_tree.h#L38):
```
    #define NAI std::numeric_limits<IdxType>::max()
```

**Comment by lizhengning** [comment]
everything is Good, succeed this time. Thanks!

**Comment by nmoehrle** [comment]
Did you use a different compiler?

**Comment by lizhengning** [comment]
No, I change the define and compile with xcode.

**Comment by nmoehrle** [comment]
Good sadly this approach does not work with nvcc...
