### ISSUE TITLE
n-channel verison result

### ISSUE THREAD

**Issue by xialang2012** [nmoehrle/mvs-texturing#49]
I have test the n-channel branch with a 10 channels file, and the results are showed below.

First, the textured result with the single band file as input images, it is very pretty.

![normal-single-band](https://cloud.githubusercontent.com/assets/14291651/16408439/5f8d96f2-3d4b-11e6-8a7e-209ef326247a.png)

Below is the textured result with 10 channels tif file as input images.
1. the result of the first band, it looks ok.

![10band-1](https://cloud.githubusercontent.com/assets/14291651/16408517/c37a5376-3d4b-11e6-8a31-478c9ea34485.png)

but, the textured result for other channels seems not very good, 
2. the result for the second band

![Uploading 10band-2.png…]()

The result for the fourth band

![10band-4](https://cloud.githubusercontent.com/assets/14291651/16408551/e903440e-3d4b-11e6-9058-415d8de1719b.png)

The result for the tenth band

![10band-6](https://cloud.githubusercontent.com/assets/14291651/16408574/02754004-3d4c-11e6-82ea-9826657db1d1.png)

**Comment by xialang2012** [comment]
Hi @nmoehrle, have you already went to holiday?

**Comment by nmoehrle** [comment]
No I am just busy with other projects and didn't know what to make of the pictures. Without more info/data I cannot actively help you, but I will happily answer questions.

Since you didn't pose a direct question I thought of this thread like an update and "jump in if you have seen similar artifacts before"

**Comment by xialang2012** [comment]
Sorry for the delay to response.
I mean the textured results for each channels are weird. 

![qq 20160714145219](https://cloud.githubusercontent.com/assets/14291651/16830925/7a9b9904-49d4-11e6-8914-a3f0a1c5e242.png)


As shown in the images, I selected some results for single channel and multi channel images. I think if the multi-channel version worked well, the textured results should be more reasonable, e.g. the results (a,c,d) showed in red oval is not very smooth, but the result for the single is more pretty.

I am not exactly know what is the problem, but I guess it seems the each channel used the same threshold to do one action, maybe the blending action or others?

**Comment by nmoehrle** [comment]
I will try to look into it next week.

**Comment by xialang2012** [comment]
Okay, thank you.

**Comment by xialang2012** [comment]
By the way, Does the mvs-texturing master branch https://github.com/nmoehrle/mvs-texturing can be built on Windows?

**Comment by xialang2012** [comment]
I have test the n-channels branch with 10 channels tif, and the content for each channel are the same. The  test result is as same as the images showed above. So I think it is not the business of the threshold.

**Comment by xialang2012** [comment]
The problem is due to the math::Vec3f when run global seam 
```
math::Vec3f
TexturePatch::get_pixel_value(math::Vec2f pixel) const {
    assert(valid_pixel(pixel));

    math::Vec3f color;
    image->linear_at(pixel[0], pixel[1], *color);
    return color;
}
```
When the channels number is great than 3, the `return color`  only contains 3 elements, while image->linear_at() works well.

**Comment by nmoehrle** [comment]
You are right that is definitely a bug in the n-channel branch
