### ISSUE TITLE
Texturing LIDAR-generated mesh 

### ISSUE THREAD

**Issue by v4ven27** [nmoehrle/mvs-texturing#54]
Hello, 

Thanks for sharing an awesome texture mapping workflow! 

I'm trying to use [this MVS texturing module](https://github.com/nmoehrle/mvs-texturing/archive/dab68acaa693275c183c254a958130ee6d29c3e4.zip) to apply texture to a mesh.

MESH: Generated from LIDAR point clouds using Poisson Reconstruction. 
IMAGES: Captured with a camera with known offsets from the LIDAR unit. 

I have an INS to which the camera and then LIDAR are both fixed: Therefore 
- I am aware of their relative orientation with respect to each other as well as the global frame. 
- The point clouds used to generate the mesh are in a global frame of reference, as is the mesh. 
- The camera's pose (camera center position and orientation) in the global frame are known.

My query is regarding camera intrinsics and extrinsics in the NVM file describing the scene. Here are my questions:
1. Should the focal length be absolute (5mm etc), or normalized like in bundler (f_n = f \* sensor_width/image_width) ?
2. What are the coordinate axes of the camera_frame? I'm assuming the standard pinhole camera  
   (X,Y,Z) ---> (left, up, forward) ? 
3. Do the quaternions in the NVM file represent rotation from camera_frame to world_frame or vice-versa?
4.  Does the camera center in the NVM file represent the translation from world origin to camera center or vice versa?

I have no issues with the pipeline when I texture a mesh directly from images by applying Bundler+PMVS+PoissonRecon. However, when I try to texture a mesh generated from LIDAR points, I run into issues where no mesh face is seen by any camera view. 

I'd really appreciate any assistance with the above questions.

Thanks!
Venkat

**Comment by nmoehrle** [comment]
1. The focal length should be normalized with respect to the larger image dimension see [MVE Math Cookbook](https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook) and [nvm bundle file parsing](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/bundle_io.cc#L113).
2. Correct - also see [MVE Math Cookbook](https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook) for further information.
3. World to camera - see [nvm bundle file parsing](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/bundle_io.cc#L117) and [fill_world_to_cam](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/camera.cc#L61).
4. It represents the position -> translation from world origin (0, 0, 0).

However I would highly suggest that you provide the scene directly in the MVE scene format. It is just a folder containing folders for each view (e.g. *scene/views/view_0000.mve/). Each such folder contains a *meta.ini* file with camera extrinsics and intrinsics as well as the associated images.
The big advantage is that you can use [`umve`](https://github.com/simonfuhrmann/mve/tree/master/apps/umve) to verify the correctness of the camera parameters. You could also use [`makescene`](https://github.com/simonfuhrmann/mve/tree/master/apps/makescene) to convert a nvm bundle file to an MVE scene and then use 'umve' for inspection.
Further, the nvm scene format support is not as thoroughly tested as MVE scenes (within mvs-texturing).
