### ISSUE TITLE
Generating textures/materials from MVE data

### ISSUE THREAD

**Issue by zharvey-welltok** [nmoehrle/mvs-texturing#55]
Hello,

I used MVE to reconstruct a 3D model and was able to load it into Blender:

<img width="1116" alt="screen shot 2016-10-07 at 4 55 09 am" src="https://cloud.githubusercontent.com/assets/20440748/19184284/5d76cf84-8c4a-11e6-9258-19f251f1b334.png">

But unfortunately this was just the mesh and not the textures/materials. I'd like to generate those as well, and load the mesh + textures/materials into Blender.  And so, the MVE community pointed me to this excellent project.

I was able to build and compile this project, and see a `mvs-texturing/build/apps/texrecon/texrecon` binary. **I assume this is the correct tool to use for generating textures/materials, so if I'm wrong about that, please correct me!**

When I run this binary without options/args, I see it takes:

    ./texrecon [options] IN_SCENE IN_MESH OUT_PREFIX

Since this is my first time out of the box I don't *believe* I need to use any of the special `[options]` and can just roll with the defaults for right now. But I have questions about the usage of the first two arguments `IN_SCENE` and `IN_MESH`:

#### `IN_SCENE`
According to the usage docs:

    IN_SCENE := (SCENE_FOLDER | BUNDLE_FILE | MVE_SCENE::EMBEDDING)

I assume that I want `MVE_SCENE:EMBEDDING` since I used MVE to generate the mesh (PLY file). When I ran MVE it generated a `MVE/` directory with the following contents in it:

* `MVE/OUTPUT_MESH_CLEAN.ply` -> the final, cleaned mesh
* `MVE/OUTPUT_MESH.ply`
* `MVE/OUTPUT.ply`
* `MVE/synth_0.out`
* `MVE/views/view_*.mve` (10 MVE files in all)

**(1) Given the above directory structure as the "output" of running MVE, what do I want the value of my `IN_SCENE` option to be?**

#### `IN_MESH`
The usage docs for this argument state:

> The mesh that you want to texture and which needs to be in the same coordinate frame as the camera parameters.

**(2) I *assume* this is the final PLY file that MVE generated, which in my case is `OUTPUT_MESH_CLEAN.ply`?**

So, altogether, it looks like my `./texrecon` command is going to look something like:

    ./texrecon <IN_SCENE> MVE/OUTPUT_MESH_CLEAN.ply ~/final_model

Where `<IN_SCENE>` is whatever the correct value is (see first question above), and where `~/final_model` is the directory where I want `texrecon` generating its outputs to.

Thanks in advance for any-and-all help!

**Comment by nmoehrle** [comment]
1. In your case `IN_SCENE` should be `MVE::undistorted` (originally the colon notations was `SCENE_DIR:VIEW_IDS:EMBEDDING` but I never implemented the selection for view ids in mvs-texturing).
2. Yes `OUTPUT_MESH_CLEAN.ply` should be the correct one.

`texrecon` will not create a folder, it is just prefixing all output files (*.obj*, *.mtl*, etc.) with `OUT_PREFIX` (e.g. *~/final_model.obj*).

The defaults are fine if you have no occluding objects within your input images, but you should specify an outlier removal method if the images contain pedestrians or moving plants.

Hope I could help.

PS. Thanks for formatting your questions properly! :-)

**Comment by zharvey-welltok** [comment]
Awesome, thanks @nmoehrle. And no worries about the formatting, I'm sort of a stickler for using markdown properly 😄 

Quick followup question if you don't mind, regarding `MVE::undistorted`; mostly just so I can start to understand `texrecon` better as I use it more. Is there any documentation (wiki, RTD, usage docs, etc.) that outlines all the different possible values (besides `::undistorted`)? If not I'd be happy to contribute some docs if you were interested, just let me know!

Thanks again!

**Comment by nmoehrle** [comment]
`EMBEDDING` is the name of an image within the views. With mve 2.0 views became folders and the images are stored as regular image files within those folders (e.g. *MVE/views/view_0000.mve/undistorted.{png,jpeg,mvei}*). You can use `UMVE` or the file system to find out which images are available.

`undistorted` is referring to the version of the `original` image where the radial lens distortion (estimated during Structure-from-Motion (`sfmrecon`)) has been removed.
It is important that you use an undistorted embedding during texturing otherwise the central assumption of pixel accurate projection does not hold.
For experimenting with the options you could however use a downscaled version of `undistorted` (e.g. `undist-L2`). Such downscaled versions are created and used if you reconstruct the scene at a lower [scale](https://github.com/nmoehrle/mve/blob/master/apps/dmrecon/dmrecon.cc#L132).

**Comment by zharvey-welltok** [comment]
Thank you!
