### ISSUE TITLE
problem of texturing .nvm file

### ISSUE THREAD

**Issue by hushanming** [nmoehrle/mvs-texturing#56]
Hi,Nils
 I use the following command on the linux and windows
`D:\der_hass-20140923>D:\vs2013\mvs-texturing-master\mvs-texturing-master\build\a
pps\texrecon\Release\texrecon.exe bundle.nvm surface-clean.ply tex`
and the result  are as follows
![1](https://cloud.githubusercontent.com/assets/18521469/19220965/3fc586be-8e6c-11e6-9f2e-efd778bbc777.JPG)

but  I use the following command
`~\texrecon.exe scene::undistorted surface-clean.ply tex`
and the result are as follows
![2](https://cloud.githubusercontent.com/assets/18521469/19221010/193f47b8-8e6d-11e6-9be4-4b10d9e5364b.JPG)

The data I used is [der_hass-20140923](http://www.gcc.tu-darmstadt.de/home/proj/mve/) on the offical website 
so what's your view about this?

**Comment by nmoehrle** [comment]
Did you create the scene from the nvm bundle?

You have to make sure that the reconstruction and the scene/bundle are in the same coordinate system.

**Comment by hushanming** [comment]
I'm not create the scene from the nvm bundle.
 Actually I don't know more details about this.Should I use the `makescene`  to make them in the same coordinate system ? 
 Do you know how to make them in the same coordinate system? 
Thank you.

**Comment by nmoehrle** [comment]
If you are not reconstructing and texturing from the same scene/bundle than they are most certainly not in the same coordinate system. This violates the central assumption within the texturing (accurate projections for the majority of the pixels).

You have to either create the MVE scene from the nvm bundle (`makescene`) or use the MVE pipeline from the beginning `makescene`, `sfmrecon`, `dmrecon`, `fssrecon` and then `texrecon`.

**Comment by hushanming** [comment]
It works!
Thank you for your reply.Thank you.
