### ISSUE TITLE
Convention of pixel coordinates

### ISSUE THREAD

**Issue by flm8620** [nmoehrle/mvs-texturing#61]
I saw [this code](https://github.com/nmoehrle/mvs-texturing/blob/181b33661d813be4daba7802184ee0ce51947daa/libs/tex/texture_view.h#L165), a 3D point is projected to 2D image of a camera, then its pixel coordinates is substracted by 0.5

I want to know which convention of pixel coordinates is adopted in this project ?
On an image, the center of first pixel's coordinates is (0.0,0.0) or (0.5, 0.5) ?

**Comment by nmoehrle** [comment]
This project is based on MVE and follows the convention that the image plane coordinates are continues from (0,0) to (width, height) and the center of the first pixel is (0.5, 0.5). This means that whenever a linear interpolated image lookup is performed (0.5, 0.5) has to be subtracted from the image plane coordinates c.f. https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook.

To answer your question: On an image the center of the first pixel's coordinates is (0.0,0.0).

Best, Nils

**Comment by flm8620** [comment]
Your answer is very clear, also is the Math Cookbook.
It's reasonable to give (0.5, 0.5) to first pixel in MVE for letting the image plane cover all pixels.
Thank you.
