### ISSUE TITLE
Patch image size problem

### ISSUE THREAD

**Issue by flm8620** [nmoehrle/mvs-texturing#62]
The [code](https://github.com/nmoehrle/mvs-texturing/blob/181b33661d813be4daba7802184ee0ce51947daa/libs/tex/generate_texture_patches.cpp#L94) in function generate_candidate():

```
    int const width = max_x - min_x;
    int const height = max_y - min_y;
```

Should be

```
    int const width = max_x - min_x + 1;
    int const height = max_y - min_y + 1;
```
Am I correct ?

**Comment by nmoehrle** [comment]
The width of an right exclusive integer interval [min, max) is max - min and we compute the right exclusive AABB:
`max_x = std::max(static_cast<int>(std::ceil(x)), max_x)` cf. [generate_texture_patches.cpp#L83](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_patches.cpp#L83)

I hope the refactoring (de62efaf) makes this code section more readable.

Writing this answer I realized that
`max_x = std::max(static_cast<int>(std::ceil(x)), max_x)`
could be rewritten as
`max_x = std::max(static_cast<int>(x) + 1, max_x)`

**Comment by flm8620** [comment]
So AABB here is always right-bottom exclusive. I think this will create a asymmetry.
I made a graph to show this:
Imagine red points are texcoords, a blue square is a pixel.
We use the convention that coords of center of pixel[0, 0] is (0.0, 0.0)
Let us ignore the `texture_patch_border` here because texture_patch_border is symmetric for cropped image
According to your code, the cropped region should be a image of 2x2, which is [2,8],[3,8],[2,9],[3,9]
While it should be a image 3x3.
![pixel_problem](https://cloud.githubusercontent.com/assets/6289981/20627542/0b27b79a-b321-11e6-8691-1b1b8a0a6773.png)

I'm not sure if I missed something.

**Comment by nmoehrle** [comment]
I think you found something there...

Following the the [MVE Math Cookbook](https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook) I subtract (0.5, 0.5) to obtain pixel coordinates from image plane coordinates [here](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/texture_view.h).
> The center of pixel (0,0) is at (0.5, 0.5), i.e. the obtained coordinates on the image plane need to be subtracted by (0.5, 0.5) to obtain pixel coordinates.

This means that I expressed the floating point texture coordinates in an integer coordinate system, following the convention used by [linear_at](https://github.com/simonfuhrmann/mve/blob/master/libs/mve/image.h#L442).
However, it seems that I made the mistake of still using the integer coordinate systems exclusive bounds. Which would mean that the width and height computation has to be inclusive as you pointed out earlier.

Does this make sense? Do you want to send a PR or should I just fix this?

Thank you!

**Comment by flm8620** [comment]
You are welcome. You can fix it directly.
