### ISSUE TITLE
Extern C linkage error

### ISSUE THREAD

**Issue by kvanhoey** [nmoehrle/mvs-texturing#66]
Hi Nils & co,

I have a very small and a bigger issue to report.

* Small: ReadMe.txt says it requires CMake version >=2.8, CMake sais cmake_minimum_required(VERSION 3.1). Since I'm having 3.0.x, I solved it by changing the requirement line to 3.0, which works.

* Bigger
I have a weird compilation problem which may or may not be due to the code, so I'd understand if you ignore it.
Compilation quickly complains about C linkage errors, see [errorOutput.txt](https://github.com/nmoehrle/mvs-texturing/files/701514/errorOutput.txt)
I have searched quite a bit but am unsure what this means. I see no "extern C" in your code, but it may have something to do with order of inclusion of extern C code into your code: https://www.gidforums.com/t-9853.html

Do you have any idea what could cause this ?

My config:
Debian 4.9.2-10 and CMake reports that all dependencies have been correctly found:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting build type to 'RELWITHDEBINFO' as none was specified.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.3") 
-- Found Git: /usr/bin/git (found version "2.1.4") 

Thank you very much.

Kenneth

**Comment by nmoehrle** [comment]
Do you compile with `-DRESEARCH=ON`?

The GCoptimization library uses `extern "C"`...

**Comment by kvanhoey** [comment]
Hi,

Thanks for the quick reply.
I have tried both: even without the research option, it gives me the same result.

Thanks.

Kenneth

**Comment by nmoehrle** [comment]
Have you been able to resolve the issue? Could you post the solution for future reference? Thanks.

**Comment by kvanhoey** [comment]
Hi,

No I haven't solved it but could compile on other (similar) systems in the lab. Meaning it's very probably a global variable or something linked to my personal account that isn't working. I'll report when I find the solution.

Anyway, thanks a lot for the time, and sorry for the bother.
