### ISSUE TITLE
has no EMBED

### ISSUE THREAD

**Issue by lukegluke** [nmoehrle/mvs-texturing#7]
After all previous steps http://www.gris.tu-darmstadt.de/projects/mvs-texturing/ have successfully finished, when I run texturing (3D model + images + camera parameters --> textured 3D model) with
$codedir/texrecon/build/texrecon scene::undistorted surface-clean.ply textured I've got error: "IMG_162138 has no embedding undistorted" (or "no EMBEDDING" for other image if it's runned with scene::EMBEDDING). I have only one idea what actions will fix this (maybe) - delete those pictures and run all process once again. Could you please help me to understand how to fix it more gently?

**Comment by nmoehrle** [comment]
The undistorted embedding is created from the original image with the parameters estimated during bundling. However, if the bundler is unable to register a camera no such embedding is created, which would result in the error you described. I'll patch the code such that it wont terminate in the absence of the embedding in the next days. To get your texturing going you can eighter remove the view(s) without an embedding from the scene, the headers of the .mve files are ASCII so you can just grep for the file and remove it from the scene folder, or edit generate_texture_views.cpp to skip views without an undistorted embedding.

**Comment by nmoehrle** [comment]
I've just merged an older pull request from a college which skips these views after checking that it wont do any harm. I hope that fixes this issue for you.
