### ISSUE TITLE
Ghosting effect on some datasets

### ISSUE THREAD

**Issue by pierotofy** [nmoehrle/mvs-texturing#70]
While processing this dataset (https://github.com/pierotofy/drone-datasets/tree/master/sheffield_park) I get a strange ghosting effect:

This might be related to the photo consistency check?

![image](https://cloud.githubusercontent.com/assets/1951843/22840612/3c4404c0-ef9c-11e6-91d8-2b248ec0888e.png)

**Comment by nmoehrle** [comment]
Yes this is related to the photo consistency check, which was designed to prevent exactly this and... failed.
The reason that the thing (btw. what is this, a golf cart pulling a boat?) is chosen to texture multiple faces is that it has a much higher gradient magnitude than the road.

It would be interesting to see why the photo consistency check failed in this case. My assumption is that that there was no consensus between the images on the true albedo.

Can you tell me something about the drones trajectory?
Did the drone fly orthogonal to the road? If multiple images show the "thing" at one location this would skew the true albedo estimation...
How many images show this part of the scene?

**Comment by pierotofy** [comment]
Hi @nmoehrle thanks for the reply! I think it's a golf cart carrying a canoe on wheels.

Yes the drone flew orthogonal to the road. There are 5 images in the sequence that depict the object:

1. 
![image](https://cloud.githubusercontent.com/assets/1951843/22854925/248e5fa2-f045-11e6-98f7-233c8ec75c54.png)

2. 
![image](https://cloud.githubusercontent.com/assets/1951843/22854929/2bcffec4-f045-11e6-9fdc-43e12ec7ff07.png)

3. 
![image](https://cloud.githubusercontent.com/assets/1951843/22854932/33724c7c-f045-11e6-9a7a-bc93f7a815c4.png)

4. 
![image](https://cloud.githubusercontent.com/assets/1951843/22854933/38f3c96e-f045-11e6-8778-fc2716871fa7.png)

5. 
![image](https://cloud.githubusercontent.com/assets/1951843/22854934/3f3237c0-f045-11e6-8591-8015176c6594.png)

From DJI_0191 to DJI_0195 included.

You can see the drone flying forward, while the cart is moving left to right.

**Comment by pierotofy** [comment]
Actually, I have to apologize, I was under the assumption that the consistency check would be turned ON by default, but that was not the case.

Turning on "gauss_clamping" for --outlier_removal worked quite well!

![image](https://cloud.githubusercontent.com/assets/1951843/23105261/704e77d6-f6aa-11e6-9f6b-28c7e1399844.png)
