### ISSUE TITLE
Faces that are not seen by any camera get culled?

### ISSUE THREAD

**Issue by soulslicer** [nmoehrle/mvs-texturing#80]
Hi all,

I happen to have a model that has a couple of faces that are not seen by the camera (although actually the kind of do, they are just partly occluded). MVS Texturing seems to delete those faces. Is there a way I can keep these faces, and maybe just texture them black?

**Comment by soulslicer** [comment]
Hi, any response from this? Is there a way to somehow disable this, or at least estimate the nearest texture region

**Comment by nmoehrle** [comment]
There are two command line options which address this: '--keep-unseen-faces' and '--skip-geometric-visibility-test'. Just run the app without arguments get a summary of the options.
