### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by highintothesky** [nmoehrle/mvs-texturing#83]
During regular install with git, cmake, make, curl fails to get Eigen during make. it says https is not supported, while it clearly is, and it works with other repositories.

system info:
Linux  4.4.0-79-generic #100-Ubuntu 
curl:
curl 7.54.1 (x86_64-pc-linux-gnu) libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

I'm guessing the url just fails, maybe bitbucket or eigen changed their versioning or release numbers.

```
$ make -j8
[  4%] Performing update step for 'ext_gco'
[ 13%] Built target ext_mve
[ 26%] Built target ext_rayint
[ 27%] Performing download step (download, verify and extract) for 'ext_eigen'
[ 29%] Performing configure step for 'ext_gco'
-- verifying file...
       file='/home/USER/Builds/texrecon/build/elibs/ext_eigen/src/3.2.8.tar.bz2'
-- MD5 hash of
    /home/USER/Builds/texrecon/build/elibs/ext_eigen/src/3.2.8.tar.bz2
  does not match expected value
    expected: '9e3bfaaab3db18253cfd87ea697b3ab1'
      actual: 'd41d8cd98f00b204e9800998ecf8427e'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/home/USER/Builds/texrecon/build/elibs/ext_eigen/src/3.2.8.tar.bz2'
   timeout='none'
-- Using src='https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2'
-- Retrying...
-- Using src='https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2'
-- Retry after 5 seconds (attempt #2) ...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/USER/Builds/texrecon/build/elibs/ext_gco/src/ext_gco-build
[ 30%] Performing build step for 'ext_gco'
[100%] Built target gco
[ 32%] No install step for 'ext_gco'
[ 33%] Completed 'ext_gco'
[ 38%] Built target ext_gco
[ 46%] Built target mrf
-- Using src='https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2'
CMake Error at /home/USER/Builds/texrecon/build/elibs/ext_eigen/src/ext_eigen-stamp/download-ext_eigen.cmake:157 (message):
  Each download failed!

    error: downloading 'https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         
    


elibs/CMakeFiles/ext_eigen.dir/build.make:89: recipe for target 'elibs/ext_eigen/src/ext_eigen-stamp/ext_eigen-download' failed
make[2]: *** [elibs/ext_eigen/src/ext_eigen-stamp/ext_eigen-download] Error 1
CMakeFiles/Makefile2:128: recipe for target 'elibs/CMakeFiles/ext_eigen.dir/all' failed
make[1]: *** [elibs/CMakeFiles/ext_eigen.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by nmoehrle** [comment]
I cannot reproduce the error on my system using the same curl version. There is a difference in the libcurl version and features of curl (e.g. HTTP2 support), but I don't think that is the problem. Do you have multiple versions of curl installed?

curl 7.54.1 (x86_64-unknown-linux-gnu) libcurl/7.54.1 OpenSSL/1.1.0f zlib/1.2.11 libpsl/0.17.0 (+libicu/59.1) libssh2/1.8.0 nghttp2/1.23.1                                                    
Release-Date: 2017-06-14                                                                       
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp                                                                           
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by highintothesky** [comment]
i removed the old curl I had installed, and manually installed curl 7.54.1, same problem. I then removed all traces of this, and installed 7.47.0 through apt-get. same thing. even on the newest version, built with the ssl flag on, I'm getting an error saying curl doesn't support https. curl says it does though:

`curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2g zlib/1.2.8
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy `

I gave up on trying to fix this weird issue and manually put the tar.gz file in the right place instead, so i can build. thanks for trying to help anyways

**Comment by nmoehrle** [comment]
I had a protocol issue today and realized that cmake does not use the curl executable but a statically linked curl lib which may or may not have https support... By default cmake is built with its own version of libcurl which does not support https, but you can use the system libcurl version when installing from scratch with `./bootstrap --system-curl && sudo make install`.

However, that still does not solve your issue, if your cmake can download https resources in other projects.
