### ISSUE TITLE
Surface Normals too strict

### ISSUE THREAD

**Issue by soulslicer** [nmoehrle/mvs-texturing#84]
I notice MVS texturing seems to not apply textures to surfaces that surface normals are too sharp. However, they are actually still visible in the camera. Does it use the dot product rule to check for visibility? Can we tune this variable?

**Comment by nmoehrle** [comment]
As you assume right we use the dot product between viewing ray and face normal to determine the visibility [here](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/calculate_data_costs.cpp#L187) the angle is hard coded to 75 degree.
Hope that helps I am sorry for the late response.

**Comment by soulslicer** [comment]
Thanks for letting me know the part of the code.
