### ISSUE TITLE
No proper input scene descriptor given

### ISSUE THREAD

**Issue by mojovski** [nmoehrle/mvs-texturing#9]
Hi Nils,

first of all, thank you very much for sharing your work! 
And, I have a small issue with mvs-texturing using my own generated mve-scene files.

When I ran texrecon, 
```
./texrecon ~/mve_data/ /media/DATAPART1/3ddata/inputmesh.ply /media/DATAPART1/3ddata/outputmesh_with_textures
```
the output is:
```
Load and prepare mesh: 
Reading PLY: 11571748 verts... 5785874 faces... done.
Warning: Zero-length normals detected: 2557 face normals, 3958 vertex normals
Generating texture views: 
No proper input scene descriptor given.
A input descriptor can be:
BUNDLE_FILE - a bundle file (currently onle .nvm files are supported)
SCENE_FOLDER - a folder containing images and .cam files
MVE_SCENE::EMBEDDING - a mve scene and embedding
```
Actually, I generated the mve views on my own.
I followed the example [here](https://github.com/simonfuhrmann/mve/blob/master/apps/makescene/makescene.cc) and have written the camera pose and the raw 8 bit images into the mve views.
You can find one of them [here](https://drive.google.com/open?id=0B2fi7-kZoDhPUUhaMEdqekZtOTg&authuser=0)

How can I debug this issue?
Is there a way to check if the mve files are correct?
Does mvs-texture require face normals, which I dont have (yet) actually?
Or maybe I miss some parameter for the cmd?

Thank you very much for your support in advance!

**UPDATE:**
After looking at your code, I saw that you require PATH::EMBEDDING format for the mve files.
When I use embedding=distorted (thats how I called when I stored the images in the mve views),
I receive this error:
```
Initialized 1359 views (max ID is 1358), took 44ms.
        Loading 100%... done. (Took 0.186s)                                     
        Generating validity masks 100%... done. (Took 0.096s)                   
        Calculating gradient magnitude 0%...terminate called recursively        
terminate called after throwing an instance of 'std::invalid_argument'
Aborted (core dumped)
```

Even when I computed the normals of the ply mesh, I get this warning:
```
Warning: Zero-length normals detected: 2557 face normals, 0 vertex normals
```

Does this affect the issue?

**UPDATE2:**
I guess I found the issue. After disabling OpenMP, the error message came along:
```
Image must be RGB or RGBA
```

Is it possible to use another DesaturateType for grey scale images?

**Comment by nmoehrle** [comment]
As you already noted we need you to specify the embedding:
```MVE_SCENE::EMBEDDING - a mve scene and embedding```
So your command should look like this:
```
/texrecon ~/mve_data/::distorted ...
```
I would not worry too much about the warning "Zero-length normals detected" if your mesh is significantly larger than 2557 faces - sadly it is normal that a reconstruction contains degenerated faces.

About the 'std::invalid_argument' I did send you an request to access the view you uploaded on Google drive. But what I assume is that something with the views is wrong:
- 0.186s to load 1359 views is just to quick
- a possible explanation for the 'std::invalid_argument' exception are view embeddings with less than 3 color channels (I will add a check...). 

You could verify that your views are correct with the UMVE application. It is shipped with the Multi-View Environment (mve/apps/umve). Check if you can open the scene and inspect the view embeddings.

**Comment by nmoehrle** [comment]
I just looked at the view you provided on drive. The problem is in fact that we do not support gray scale images at the moment - I will open an issue.
Sorry this should have been communicated.

**Comment by mojovski** [comment]
Hi Nils,
no problem. :) Finally, your paper is called "there will be colour".

In the mean while, I will convert my grey scale images to RGB images with R=G=B=greyvalue.
Would be great, if you keep me updated on this issue if the issue get fixed in the project.

Thank you very much!

**Comment by nmoehrle** [comment]
I already implemented a check to give a meaningful error message in case of grey scale images and opened a ticket requesting support for them. I will give you a heads up when the support has been implemented.

**Comment by MrWarc** [comment]
hi nmoehrle,
I also meet the same question. When running the texrecon,the output is "No proper input scene descriptor given".I wonder if you can give a proper file format about SCENE_FOLDER.
thanks a lot.
