### ISSUE TITLE
How to run mvs texturing with cam,mesh and image files?

### ISSUE THREAD

**Issue by ManishSahu53** [nmoehrle/mvs-texturing#93]
I have a mesh.ply file and .cam and .jpg files in cam folder. 
I am running this command "./texrecon cam  mesh.ply textured "
I got this error 
"Load and prepare mesh: 
Reading PLY: 478986 verts... 956298 faces... done.
Generating texture views: 
        Loading 0%...Could not load image header of /home/indshine-2/Downloads/openMVG_Build/Linux-x86_64-RELEASE/cam/cam/DJI_0001.JPG
/home/indshine-2/Downloads/openMVG_Build/Linux-x86_64-RELEASE/cam/cam/DJI_0001.JPG: No such file or directory"
Then I included cam/cam folder and moved my .cam and .jpg data in it and again ran.
Generating texture views: 
No proper input scene descriptor given.
A input descriptor can be:
BUNDLE_FILE - a bundle file (currently onle .nvm files are supported)
SCENE_FOLDER - a folder containing images and .cam files
MVE_SCENE::EMBEDDING - a mve scene and embedding

 Can you tell me what am I missing here?
Thank You.

**Comment by nmoehrle** [comment]
Have the cam and jpg the same prefix?

**Comment by ManishSahu53** [comment]
Yes they same name with .cam and .jpg part different. I exported .cam file from openmvg module.

**Comment by nmoehrle** [comment]
So there is a issue with the concatenation of paths? The file _/home/indshine-2/Downloads/openMVG_Build/Linux-x86_64-RELEASE/cam/cam/DJI_0001.JPG_ does not exist but the file _/home/indshine-2/Downloads/openMVG_Build/Linux-x86_64-RELEASE/cam/DJI_0001.JPG_ does?

**Comment by ManishSahu53** [comment]
no. opposite.
Actually I did 2 runs.
1 run -- images are in cam folder. So the program thrown an error stating "cam/cam/*.jpg doesnt exit".
2 run -- I moved my images to cam/cam folder then ran the program now it gives an error stating 
"Generating texture views:
No proper input scene descriptor given.
A input descriptor can be:
BUNDLE_FILE - a bundle file (currently onle .nvm files are supported)
SCENE_FOLDER - a folder containing images and .cam files
MVE_SCENE::EMBEDDING - a mve scene and embedding"

**Comment by nmoehrle** [comment]
But on the first run, where `texrecon` complains about the file not existing, it complains about a file in _cam/cam/_ although the file is in _cam/_ or not? Can you try running the first one again with cam*/*? Just to be sure it isn't something stupid with the path concatenation...

**Comment by ManishSahu53** [comment]
ok Sure I will try to run it again.
Just to make sure I am doing ok here. I will put .cam and .jpg files in cam folder.
mesh.ply in current folder and a textured folder to put textured mesh. Thanks

**Comment by nmoehrle** [comment]
'./texrecon cam/ mesh.ply textured'

**Comment by nmoehrle** [comment]
Thanks for providing the files, I can reproduce the issue - investigating.

**Comment by ManishSahu53** [comment]
Thank You very much. I am eagerly waiting for your response.

**Comment by nmoehrle** [comment]
Sorry that this took so long I must have broken this in when merging #91, please check if this fix works for you.

Best

**Comment by ManishSahu53** [comment]
@nmoehrle the program made some progress but ended with segmentation fault. Can you running with the dataset in th link?
I have 32 GB ram pc so I think memory isnt a problem

**Comment by ManishSahu53** [comment]
It is working now. Thank you very much

**Comment by 18500864609** [comment]
@ManishSahu53  I met a same situation as you ,can you give me an advice on how to prepare the cam and the images? thanks a lot
